### ISSUE TITLE
portable?

### ISSUE THREAD

**Issue by wincmd64** [ElektroStudios/Easy-Link-File-Viewer#10]
> Portable application. Just copy the software anywhere.

and what about user.config in local appdata?

**Comment by ElektroStudios** [comment]
I am very sorry for the delay in offering a response, but I have had this project quite forgotten and abandoned.

Responding to your question, let me tell you that the auto-generated file in the local appdata directory does not influence the portability of the program, being understood as an application that does not require installation, and can be used from, for example, a USB device.

In the "Easy Link File Viewer.exe.config" file located next to the portable executable, you can modify and set the default values of the program options:
```xml 
<setting name="VisualThemeIndex" serializeAs="String">
    <value>0</value>
</setting>
<setting name="FontSize" serializeAs="String">
    <value>10</value>
</setting>
```
The value you specify for those options will take effect immediately the first time you start the program, as long as the auto-generated file does not exist in the local app data directory with different options.

In any case, the auto-generated file in the local app data directory is unnecessary and is something that will no longer be necessary in the next release. The methodology for saving and loading user preferences will be changed so that they are stored in the same directory of the portable executable.

This may take me some time (from few days, to some weeks) as there are several other Issues in this project that I also need to try offer solutions to. Please be patient.

Sincerely,
Elektro.

**Comment by ElektroStudios** [comment]
The fix has already been implemented in the new source code update. See [change log](https://github.com/ElektroStudios/Easy-Link-File-Viewer/blob/master/Docs/CHANGELOG.md). This was done using [Jot](https://github.com/anakic/Jot).

Please wait for the new release to be published.

If you have more questions feel free to follow this debate. For now, I consider it finished.
